export const productTitle =
  "毎月25万円の印税が振り込まれるまでにやったこと、全部書きました";

export const categories = [
  {
    id: "planning",
    title: "企画・素材を固める",
    description: "経験や考えを、原稿に使える材料へ変えます。",
    chapters: "第0章〜第2章",
  },
  {
    id: "structure",
    title: "構成を作る",
    description: "読者が迷わない順番と、章の役割を決めます。",
    chapters: "第3章",
  },
  {
    id: "drafting",
    title: "本文を書く",
    description: "音声、既存資料、AIを使って本文を組み立てます。",
    chapters: "第3章〜第5章",
  },
  {
    id: "voice",
    title: "文章を作り込む",
    description: "説明書のような文章から、書き手の言葉を取り戻します。",
    chapters: "第3章",
  },
  {
    id: "review",
    title: "編集・レビューする",
    description: "複数の視点を集め、採用する修正を自分で決めます。",
    chapters: "第4章・第5章",
  },
  {
    id: "publish",
    title: "出版前・KDP",
    description: "公開前の事実、日本語、安全、整合性を確認します。",
    chapters: "第6章〜第8章",
  },
  {
    id: "grow",
    title: "出版後に育てる",
    description: "反応を受けて、本と制作ルールを更新します。",
    chapters: "第9章・第10章",
  },
] as const;

export const articles = [
  {
    number: "01",
    slug: "longform-with-codex",
    href: "/library/longform-with-codex",
    title: "AIで長文原稿を1冊仕上げる、現在の制作フロー",
    summary:
      "音声入力、AIからの逆質問、2種類のMarkdown、チャットの引き継ぎ、複数AIのレビューを、私が今どの順番で使っているのかを、1冊分の実例とともに紹介します。",
    originLabel: "購入者アンケートを反映",
    primaryCategory: "本文を書く",
    categoryId: "drafting",
    tags: ["企画・素材を固める", "編集・レビューする"],
    chapters: "第3章〜第5章",
    verified: "2026年7月",
    environment: "Mac／Codexデスクトップアプリ／Web版ChatGPT／Claude",
    status: "現在も使用中",
  },
  {
    number: "02",
    slug: "ai-voice-before-after",
    href: "/library/ai-voice-before-after",
    title: "AIっぽさを消す、あおいの原稿ビフォー・アフター",
    summary:
      "AIの案、私が感じた違和感、追加した材料、完成稿を並べ、何を直し、何を残したのか、その判断基準を公開します。",
    originLabel: "購入者アンケートを反映",
    primaryCategory: "文章を作り込む",
    categoryId: "voice",
    tags: ["本文を書く", "編集・レビューする"],
    chapters: "第3章",
    verified: "2026年7月",
    environment: "過去ログ／音声回答／完成原稿",
    status: "判断基準は現在も使用中",
  },
  {
    number: "03",
    slug: "codex-book-rewrite",
    href: "/library/codex-book-rewrite",
    title: "1年前の本を、いまの基準で育て直す。Codex既刊リライトの実録",
    summary:
      "価値の残る既刊を選び、本文、監査、挿絵、巻末、最終DOCXまで育て直した実例を、Codexに任せたことと著者が決めたことに分けて紹介します。",
    originLabel: "現在の既刊リライト実務を反映",
    primaryCategory: "出版後に育てる",
    categoryId: "grow",
    tags: ["本文を書く", "編集・レビューする"],
    chapters: "第3章〜第5章・第10章",
    verified: "2026年8月",
    environment: "Mac／Codexデスクトップアプリ",
    status: "既刊5冊で実施",
  },
] as const;

export const downloads = [
  {
    number: "01",
    title: "全書籍共通ルール",
    description: "日本語・事実・安全について、どの本でも守るルールです。",
    file: "01-common-writing-rules.md",
    downloadName: "01_全書籍共通ルール.md",
    timing: "新しい本の作業を始めるとき",
    editing: "書き換えて使用",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#markdown",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "内容を読み、自分の執筆方針に合わないルールを削る。",
      "今後もすべての本で守るルールだけを残す。",
      "本書専用ルールと原稿に添えて、作業開始時にAIへ渡す。",
    ],
  },
  {
    number: "02",
    title: "本書専用ルール｜テンプレート＋参考記入例",
    description:
      "1冊ごとの読者、文体、公開範囲などを整理するテンプレートと、強い実績数字を扱う本の参考記入例です。",
    file: "02-book-specific-rules.md",
    downloadName: "02_本書専用ルール.md",
    timing: "構成を決める前、または執筆中",
    editing: "テンプレートは書き換えて使用／記入例は参考として閲覧",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#markdown",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "読者、伝えたいこと、公開範囲、文体などの空欄を埋める。",
      "執筆中に感じた違和感から、その本だけで守るルールを追加する。",
      "全書籍共通ルールと原稿に添えて、AIへ渡す。",
    ],
  },
  {
    number: "03",
    title: "AIからの逆質問",
    description: "原稿に足りない体験、感情、判断理由を引き出す依頼文です。",
    file: "03-reverse-questions.md",
    downloadName: "03_AIからの逆質問.md",
    timing: "構成や初稿に書き手自身の材料が足りないとき",
    editing: "そのまま使用可能",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#questions",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "初稿または構成と、2種類の執筆ルールをAIへ渡す。",
      "依頼文を貼り、足りない材料を引き出す質問を5問ずつ作ってもらう。",
      "音声などで回答し、本文を直す前に反映先と整理案を確認する。",
    ],
  },
  {
    number: "04",
    title: "AI並行レビュー",
    description: "複数AIへ同じ条件でレビューを頼む共通依頼文です。",
    file: "04-parallel-review.md",
    downloadName: "04_AI並行レビュー.md",
    timing: "原稿が完成に近づいたとき",
    editing: "対象読者と文体を書き換えて使用",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#parallel-review",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "原稿から個人情報や、共有してはいけない情報を外す。",
      "同じ原稿、執筆ルール、依頼文を、各AIの新しいチャットへ渡す。",
      "全AIの回答が揃うまで本文を直さず、レビュー全文を保存する。",
    ],
  },
  {
    number: "05",
    title: "3段階の統合判定",
    description: "複数AIの意見を、多数決にせず再分類する依頼文です。",
    file: "05-review-integration.md",
    downloadName: "05_3段階の統合判定.md",
    timing: "すべてのAIレビューが揃ったあと",
    editing: "そのまま使用可能",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#parallel-review",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "原稿、2種類の執筆ルール、複数AIのレビュー全文をCodexへ渡す。",
      "依頼文を貼り、指摘を3段階へ再分類した案を作ってもらう。",
      "本文へ反映する前に、自分で採用・見送りを決める。",
    ],
  },
  {
    number: "06",
    title: "出版前チェック",
    description: "AIレビュー後に、人間が最後に確認するための一覧です。",
    file: "06-final-checklist.md",
    downloadName: "06_出版前チェック.md",
    timing: "KDPへ登録する直前",
    editing: "そのまま使用可能",
    related: "出版前・KDPの工程",
    relatedHref: "/library#publish",
    verified: "2026年7月",
    version: "v1.1",
    steps: [
      "KDPへ登録する直前に、一覧を上から確認する。",
      "AIだけに任せず、人間が原稿を最初から最後まで読む。",
      "修正後は該当箇所の前後と、公開ファイルをもう一度確認する。",
    ],
  },
  {
    number: "07",
    title: "チャット引き継ぎテンプレート",
    description: "長くなった作業を、次のチャットへ安全に渡すためのひな型です。",
    file: "07-chat-handoff.md",
    downloadName: "07_チャット引き継ぎテンプレート.md",
    timing: "構成検討から本文制作へ移るとき",
    editing: "書き換えて使用",
    related: "長文原稿を1冊仕上げる現在の方法",
    relatedHref: "/library/longform-with-codex#handoff",
    verified: "2026年7月",
    version: "v1.0",
    steps: [
      "現在のチャットへ、この項目に沿った引き継ぎを作るよう依頼する。",
      "途中案と確定事項、本文の正本が混ざっていないか自分で確認する。",
      "最新本文、執筆ルール、必要資料と一緒に、新しいチャットへ渡す。",
    ],
  },
  {
    number: "08",
    title: "Codex既刊リライト開始キット",
    description: "既刊の選定から最終DOCXまで、実作業を8STEPで進める手順と依頼文です。",
    file: "08-codex-book-rewrite-starter-kit.md",
    downloadName: "08_Codex既刊リライト開始キット.md",
    timing: "既刊をリライトするとき",
    editing: "書き換えて使用",
    related: "Codex既刊リライトの実録",
    relatedHref: "/library/codex-book-rewrite",
    verified: "2026年8月",
    version: "v1.0",
    steps: [
      "直す価値のある既刊を1冊選ぶ。",
      "変えないものと変えるものを決める。",
      "本文を変更せず、修正候補だけを出してもらう。",
    ],
  },
] as const;
